openapi: 3.0.1

info:
  title: gpt-2-evaluate
  description: ' '
  version: "0.1"
servers:
 - url: https://gpt2-large-gpt-2-evaluate-gkswjdzz.endpoint.ainize.ai
paths:
  /evaluate:
    post:
      tags:
      - gpt-2-large
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              example: [
                8117, 318, 257, 220, 933, 12754, 3303, 286
              ]
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
                example: {
                  "score": 23.681757785577105
                }
        '400':
          description: Bad Request
        '500':
          description: Server side error
tags:
- name: gpt-2-large